-- 01-create-workshop-admin.sql
-- Creates the WORKSHOP_ADMIN user and workshop_users tracking table.
-- Runs as SYS via gvenzl entrypoint.

ALTER SESSION SET CONTAINER = FREEPDB1;

-- Create admin user (if not exists)
DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_count FROM dba_users WHERE username = 'WORKSHOP_ADMIN';
  IF l_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER WORKSHOP_ADMIN IDENTIFIED BY "WorkshopApp2026" QUOTA UNLIMITED ON USERS';
  END IF;
END;
/

-- Grant roles and privileges
GRANT DB_DEVELOPER_ROLE TO WORKSHOP_ADMIN;
GRANT SODA_APP TO WORKSHOP_ADMIN;
GRANT CREATE USER TO WORKSHOP_ADMIN;
GRANT DROP USER TO WORKSHOP_ADMIN;
GRANT ALTER USER TO WORKSHOP_ADMIN;
GRANT CREATE SESSION TO WORKSHOP_ADMIN WITH ADMIN OPTION;
GRANT DB_DEVELOPER_ROLE TO WORKSHOP_ADMIN WITH ADMIN OPTION;
GRANT SODA_APP TO WORKSHOP_ADMIN WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO WORKSHOP_ADMIN WITH ADMIN OPTION;
GRANT SELECT_CATALOG_ROLE TO WORKSHOP_ADMIN WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO WORKSHOP_ADMIN;
GRANT CREATE ANY VIEW TO WORKSHOP_ADMIN;
GRANT CREATE ANY INDEX TO WORKSHOP_ADMIN;
GRANT CREATE ANY PROCEDURE TO WORKSHOP_ADMIN;
GRANT INSERT ANY TABLE TO WORKSHOP_ADMIN;
GRANT SELECT ANY TABLE TO WORKSHOP_ADMIN;

-- Switch to admin schema for remaining objects
ALTER SESSION SET CURRENT_SCHEMA = WORKSHOP_ADMIN;

-- Workshop users tracking table
CREATE TABLE workshop_users (
    id            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    schema_name   VARCHAR2(128) NOT NULL UNIQUE,
    display_name  VARCHAR2(200),
    email         VARCHAR2(255),
    status        VARCHAR2(20) DEFAULT 'active' CHECK (status IN ('active', 'locked', 'teardown')),
    progress      JSON DEFAULT '{}',
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
    last_active   TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMIT;
